#!/usr/bin/env bash
# Smoke test: run `yarn build` on each alerte-secours backend service against
# the dev version of @modjo/core, with safe swap-symlink + automatic restore.
#
# What it does:
#   1. Backs up the current vendored @modjo/core (rename → .bak)
#   2. Symlinks @modjo/core to the dev tree (this repo's packages/core)
#   3. Runs `yarn build` in each service
#   4. ALWAYS restores the original via `trap`, even on crash / Ctrl-C
#
# This touches only:
#   - <ALERTE_SECOURS>/node_modules/@modjo/core    (swap symlink)
#   - <ALERTE_SECOURS>/services/<svc>/build/       (regenerated by build)
#
# Nothing in the dev modjo repo is mutated.

set -euo pipefail

DEV_CORE="${DEV_CORE:-/home/jo/lab/devthefuture/modjo/packages/core}"
ALERTE_SECOURS="${ALERTE_SECOURS:-/home/jo/lab/alerte-secours/apps/alerte-secours}"
SERVICES=(api files tasks watchers)

VENDORED="$ALERTE_SECOURS/node_modules/@modjo/core"
BACKUP="$VENDORED.bak.smoke-$$"

if [[ ! -d "$DEV_CORE" ]]; then
  echo "ERROR: DEV_CORE not found: $DEV_CORE" >&2
  exit 1
fi
if [[ ! -d "$VENDORED" ]] && [[ ! -L "$VENDORED" ]]; then
  echo "ERROR: vendored @modjo/core not found at $VENDORED" >&2
  exit 1
fi

restore() {
  local rc=$?
  echo ""
  echo "[restore] cleaning up swap …"
  if [[ -L "$VENDORED" ]]; then
    rm "$VENDORED"
  elif [[ -d "$VENDORED" ]]; then
    rm -rf "$VENDORED"
  fi
  if [[ -e "$BACKUP" ]]; then
    mv "$BACKUP" "$VENDORED"
    echo "[restore] original @modjo/core restored"
  fi
  exit $rc
}
trap restore EXIT INT TERM

echo "[swap] backing up vendored @modjo/core → $BACKUP"
mv "$VENDORED" "$BACKUP"

echo "[swap] symlinking @modjo/core → $DEV_CORE"
ln -s "$DEV_CORE" "$VENDORED"

# The dev core's node_modules contain its dependencies (lodash, nctx, yup, …).
# When a service requires @modjo/core, Node resolves transitive deps starting
# from the symlink target — so the dev core's node_modules must exist.
if [[ ! -d "$DEV_CORE/node_modules" ]] && [[ ! -L "$DEV_CORE/node_modules" ]]; then
  echo "WARN: $DEV_CORE/node_modules missing — run yarn at modjo repo root first" >&2
fi

echo ""
echo "=========================================="
echo " Running smoke build on each service"
echo "=========================================="

# Use devbox-provided node (alerte-secours pins nodejs_20 via devbox.json).
# Sentry profiling-node ships a prebuilt native binary tied to the Node ABI;
# running with the wrong major (e.g. system Node 24) fails on require.
NODE_BIN="$(cd "$ALERTE_SECOURS" && devbox run --quiet -- which node 2>/dev/null | tail -1)"
if [[ -z "${NODE_BIN:-}" ]] || [[ ! -x "$NODE_BIN" ]]; then
  echo "ERROR: could not resolve node via devbox at $ALERTE_SECOURS" >&2
  echo "       try: cd $ALERTE_SECOURS && devbox install" >&2
  exit 3
fi
echo "[node] using $NODE_BIN ($("$NODE_BIN" --version))"

PASS=()
FAIL=()
for svc in "${SERVICES[@]}"; do
  SVC_DIR="$ALERTE_SECOURS/services/$svc"
  if [[ ! -d "$SVC_DIR" ]]; then
    echo "[skip] $svc — directory missing"
    continue
  fi
  echo ""
  echo "------- $svc -------"
  if (cd "$SVC_DIR" && timeout 120 "$NODE_BIN" src/index.js build); then
    echo "[ok]   $svc build succeeded"
    PASS+=("$svc")
  else
    rc=$?
    echo "[fail] $svc build failed (exit $rc)"
    FAIL+=("$svc")
  fi
done

echo ""
echo "=========================================="
echo " Summary"
echo "=========================================="
echo "PASS: ${PASS[*]:-(none)}"
echo "FAIL: ${FAIL[*]:-(none)}"
if [[ ${#FAIL[@]} -gt 0 ]]; then
  exit 2
fi
